title = "Deginner"
baseurl = "http://deginner.com"
languageCode = "en-us"

[params]
  # Meta parameters.
  language = "en"
  encoding = "utf-8"
  keywords = ["Python", "JavaScript", "Test"]
  description = "A static website that has no description"

  # Top section of the website.
  topAnchor = "top"
  logo = "http://i.imgur.com/MINlVoa.png"
  title = "Deginner"
  tagline = "Something. Very. Interesting"

  # Top actions. Action format: [text, anchor]
  mainAction = ["Action", "Contact"]
  secondaryAction = ["Projects &nbsp; ›", "Projects"]

[blackfriday]
  hrefTargetBlank = true
